version: '3.9'

services:
  tastebin:
    build: .
    restart: always
    ports:
      - "3030:3000"
    networks:
      - tastebin_app
  
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tastebin
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - ./db-data/mongo/:/data/db
    networks:
      - tastebin_app

networks:
  tastebin_app:    
    driver: bridge